version: '3'

services:
  gen-t-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
